server:
  port: 8081
  servlet:
    context-path: /microservices

spring:
  datasource:
    url: jdbc:h2:mem:salary_processing_db;MODE=PostgreSQL
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  docker:
    compose:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
      transaction-id-prefix: tx-
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.study.microservices.salaryprocessingservice.model.dto
        spring.json.value.default.type: com.study.microservices.salaryprocessingservice.model.dto.EmployeePaymentDto
      enable-auto-commit: false
      isolation-level: read_committed
    listener:
      ack-mode: manual_immediate
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

logging:
  level:
    org.springframework.kafka: INFO
    org.springframework.transaction: TRACE
    org.springframework.kafka.transaction: DEBUG

