server:
  port: 8081

spring:
  devtools:
    livereload:
      enabled: false
  webflux:
    base-path: /marketplace
  data:
    mongodb:
      database: user_data

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG

