eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  application:
    name: products-service
  datasource:
    url: jdbc:h2:file:~/products_db;AUTO_SERVER=true
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        format_sql: true
#        show_sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
server:
  port: 0
  error:
    include-message: always
    include-binding-errors: always

