spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
#        generate_statistics: true

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.transaction: DEBUG

togglz:
  features:
    get_all_employees:
      enabled: true
  console:
    path: /togglz-console
    secured: false
    use-management-port: false
    enabled: true