server:
  port: 8080
  servlet:
    context-path: /microservices

#JPA
spring:
  datasource:
    url: jdbc:h2:mem:employees_db
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop