server:
  port: 8080
  servlet:
    context-path: /microservices

spring:
  datasource:
    url: jdbc:h2:mem:employees_db;MODE=PostgreSQL
    username: sa
    password: sa
    driverClassName: org.h2.Driver
#    url: jdbc:postgresql://localhost:5432/employee-service
#    username: postgres
#    password: admin
#    driverClassName: org.postgresql.Driver
  sql:
    init:
      data-locations: classpath:data.sql
#     For the first database INIT with data.sql set mode: ALWAYS, then set NEVER
#      mode: ALWAYS
  jpa:
    open-in-view: false
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
  flyway:
    enabled: true